### PR TITLE
Fix/python version

### PR DESCRIPTION
**Pull request by mthcrts**
`find_package` does not support version number as "2.7.15rc1" (current Python version on Ubuntu 18.04).

The regular expression removes the suffix starting with a letter: "rc...", "alpha...".

### CODE REVIEW

**Comment by thelfer** [comment]
Hi Matthieu,
Thanks for the feed-back. However, the github repository is only a read only mirror of the SVN repository (to which you have/can have read-write access).
I'll commit the changes to trunk tomorrow and backport it to the rliv-3.1 branch. This will be reflected to the github repository soon after.
Thanks again,
Best,
Thomas

**Comment by mthcrts** [comment]
Unfortunately it is not sufficient to build on ubuntu 18.04...

**Comment by thelfer** [comment]
Indeed, it works for python3 on Ubuntu 18.04.
Trying to find a fix.
Thomas

**Comment by thelfer** [comment]
So far, compiling with you patch is ok. Have launched `make check`.

**Comment by thelfer** [comment]
Dear Matthieu,

It seems like `Boost/Python` is broken if a very strange way, as it works with `Python 3`.
The issue seems related to Issue 173: see https://github.com/boostorg/python/issues/173.

However, I can't figure out why the treatment of visibility flags is different when using `Python 2` and `Python 3`. Nevertheless, the workaround here is to define the `enable-broken-boost-python-module-visibility-handling` variable at  `cmake` invokation, as follows:

~~~~
cmake ../tfel-3.1.2 -Denable-aster=ON -Denable-python-bindings=ON -DPython_ADDITIONAL_VERSIONS=2.7 -Denable-broken-boost-python-module-visibility-handling=ON 
~~~~

You will then see this wonderful output when running the tests:

~~~~
1096/1096 Test #1096: ComputeTensorDeterminantSecondDerivativeTest ...................................................   Passed    0.00 sec

100% tests passed, 0 tests failed out of 1096

Total Test time (real) = 142.25 sec
[100%] Built target check
~~~~

With kind regards,
Thomas

**Comment by thelfer** [comment]
Your patch was included in:

- revision 2145 in trunk
- revision 2146 in rliv-3.1

**Comment by mthcrts** [comment]
Thanks Thomas!
I found the missing `init_xxx` symbol in the boost-python modules. By adding the compilation flag, the symbol is present and the modules can be imported.
:+1:

**Comment by thelfer** [comment]
Great !

**Pull request closed without merging**
