### PR TITLE
Mohr Coulomb changes

### PR DESCRIPTION
**Pull request by nagelt**
Alterations to surface smoothing procedure in order to make yield function C2 continuous. I tried to catch everything but when I compiled TFEL it didn't seem to recognise the changes (nothing to do during compile); so I'm not sure whether it compiles. Maybe you can take a look.

Similar merge request pending in OGS, tests there run.

### CODE REVIEW

**Comment by thelfer** [comment]
Hi Thomas,
Thanks for this contribution.
Have you tried a `make check` ? Indeed, your changes would only affect the tests.
Also, as your evolutions may affect the results (compared to previous versions), it would also be nice to update the release-notes of the version 4.0 in a section dedicated to `TFEL/Material` and in a section `Known incompatibilites`.
Best,
Thomas
P.S. : Please note that I will reject the pull request as the github repository is just a mirror of an internal `SVN` repository with private access. So I'll make the merge myself.

**Comment by nagelt** [comment]
I'm on it ...

**Comment by nagelt** [comment]
make check works fine .. .100% passed.
I added a short text in the release notes...

**Comment by thelfer** [comment]
By curiosity, is there any proof that this new version is superior to the previous one ?

**Comment by nagelt** [comment]
No ... and I didn't observe any drastic change in my tests ... one test came back with slightly fewer iterations, but not much ...  I just came across the paper and adapted the code because it sounded plausible and I was curious ... the visual inspection of the yield surface in the deviatoric plane looks good ... the changes are subtle .. I'm adding a plot of one of the corners from the pi-plane test ... 

[MCAS_C2_zoom.pdf](https://github.com/thelfer/tfel/files/5858578/MCAS_C2_zoom.pdf)

**Comment by thelfer** [comment]
I integrated your patches in my development branch. I will be available in github soon (github is only a mirror of our internal repository for the moment).

**Pull request closed without merging**
