### PR TITLE
Add Ansys to the homepage list

### PR DESCRIPTION
**Pull request by Irvise**
Hi Thomas,

I have been meaning to do this simple PR for a long time but never got around doing it. I personally do not use Ansys, but I think it will give MFront a bit more visibility to new visitors if Ansys is present in the homepage list.

Also, thank you for letting user expressions inside behavioral bricks! That perfectly solves my Norton creep modelling needs.

Best regards,
Fer

### CODE REVIEW

**Comment by thelfer** [comment]
Thanks @Irvise, I appreciate. Happy to see that MFront was helpful !

**Comment by Irvise** [comment]
Hi Tomas, I do not know if you closed the issue by mistake or knowingly. Just pointing it out :)

**Comment by thelfer** [comment]
> Hi Tomas, I do not know if you closed the issue by mistake or knowingly. Just pointing it out :)

My bad, I though that I accepted the merge request. Sorry !

**Comment by Irvise** [comment]
No problem. Its a pleasure to help ^^, thanks!

**Pull request closed without merging**
